### ISSUE TITLE
add cache support for models and CLI

### ISSUE THREAD

**Issue by jtarchie** [ai-action/setup-ollama#40]
## Problem

Each task run, the binary and model must be downloaded, again. That's a lot of bytes.

## Suggested Solution

Use of [action/cache](https://github.com/actions/cache) can be done via [npm](https://github.com/actions/setup-go/blob/0aaccfd150d50ccaeb58ebd88d36e91967a5f35b/src/cache-save.ts#L2) or have extra YAML explaining what to add to the job.

**Comment by jtarchie** [comment]
I see that the cli is cached, my apologies.
I am trying to come up with the syntax to cache the models.

**Comment by jtarchie** [comment]
I just need to figure out how to find the working directory for ollama models:

```yaml
      - uses: actions/cache@v4
        with:
          path: .ollama
          key: ollama-models
```

Tried this and it did not work.

**Comment by jtarchie** [comment]
Got it:

```yaml
      - uses: actions/cache@v4
        with:
          path: ~/.ollama
          key: ollama-models
```

**Comment by remarkablemark** [comment]
Nice @jtarchie! Would you like to update the README?

**Comment by remarkablemark** [comment]
I added an example on how to cache in #41:

```yml
- name: Cache ollama
  uses: actions/cache@v4
  with:
    path: ~/.ollama
    key: ${{ runner.os }}-ollama
```
